version: '3.8'
services:
  app:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
     - ./content:/usr/share/nginx/html
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
    environment:
      - NGINX_HOST=menu.online
      - NGINX_PORT=80
      - URL=menu.online
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare